name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install EB CLI
        run: |
          sudo apt-get update
          sudo apt-get install python3
          sudo apt-get install python3-pip
          pip3 install --upgrade setuptools pip
          pip3 install awsebcli

      - name: Deploy to Elastic Beanstalk
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker pull liran86/ai_debugger_server:latest
          docker pull liran86/ai_debugger_frontend:latest
          eb deploy Aidebugger-env
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
